name: fs_graphs
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-276.0.dev

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  graphs: ^2.3.1
  collection: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
